version: "3"
services:
  front:
    container_name: repgram_front
    build:
      context: ./front
      dockerfile: Dockerfile_${ENV}
    ports:
      - 4000:4000
    depends_on:
      - backend
    tty: true
    volumes:
      - ./front:/usr/src/app
    working_dir: "/usr/src/app"

  backend:
    container_name: repgram_backend
    build:
      context: ./backend
      dockerfile: Dockerfile_${ENV}
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    volumes:
      - ./backend:/go/src/api
    working_dir: "/go/src/api"
    environment:
      DB_HOST: repgram_db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_ROOTPASS: password
      DB_USERNAME: root
      DB_USERPASS: password
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      BUCKET_NAME: repgram-production

  db:
    image: mysql
    container_name: repgram_db
    command: >
      mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
